### ISSUE TITLE
Upload Directory returns Error: Request failed with status code 400. 

### ISSUE THREAD

**Issue by ltfschoen** [NebulousLabs/nodejs-skynet#48]
In this PR I've tried to upload the build/ directory of my React project https://github.com/ltfschoen/ethquad/pull/18/files#diff-ea539d18659745b70c0740f87d739b5dR57 using `skynet.uploadDirectory` by following the docs https://nebulouslabs.github.io/skynet-docs/?javascript--node#uploading-a-directory. But it generates the following error `Error: Request failed with status code 400`, see logs below (note that I've added some console.logs before the error). It seems strange that it's assigning the folder's absolute path to the `filename` property of the `params` (i.e. `params: { filename: '/Users/ls/code/src/ltfschoen/ethquad/client/build' },`):
```
opts {
  portalUrl: 'https://siasky.net',
  endpointPath: '/skynet/skyfile',
  portalFileFieldname: 'file',
  portalDirectoryFileFieldname: 'files[]',
  customFilename: '',
  dryRun: false,
  APIKey: undefined,
  customUserAgent: 'Sia-Agent'
}
FILE:  /Users/ls/code/src/ltfschoen/ethquad/client/build/favicon.ico
filepath favicon.ico
FILE:  /Users/ls/code/src/ltfschoen/ethquad/client/build/index.html
filepath index.html
FILE:  /Users/ls/code/src/ltfschoen/ethquad/client/build/ipfs/development/index.html
filepath ipfs/development/index.html
FILE:  /Users/ls/code/src/ltfschoen/ethquad/client/build/ipfs/development/pin.json
filepath ipfs/development/pin.json
FILE:  /Users/ls/code/src/ltfschoen/ethquad/client/build/logo192.png
filepath logo192.png
FILE:  /Users/ls/code/src/ltfschoen/ethquad/client/build/logo512.png
filepath logo512.png
FILE:  /Users/ls/code/src/ltfschoen/ethquad/client/build/main.js
filepath main.js
FILE:  /Users/ls/code/src/ltfschoen/ethquad/client/build/manifest.json
filepath manifest.json
FILE:  /Users/ls/code/src/ltfschoen/ethquad/client/build/robots.txt
filepath robots.txt
FILE:  /Users/ls/code/src/ltfschoen/ethquad/client/build/skynet/index.html
filepath skynet/index.html
url https://siasky.net/skynet/skyfile
params { filename: '/Users/ls/code/src/ltfschoen/ethquad/client/build' }
dryrun false

Error: Request failed with status code 400
    at createError (/Users/ls/code/src/ltfschoen/ethquad/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/ls/code/src/ltfschoen/ethquad/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/ls/code/src/ltfschoen/ethquad/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: {
    url: 'https://siasky.net/skynet/skyfile',
    method: 'post',
    params: { filename: '/Users/ls/code/src/ltfschoen/ethquad/client/build' },
    data: FormData {
      _overheadLength: 1625,
      _valueLength: 0,
      _valuesToMeasure: [Array],
      writable: false,
      readable: true,
      dataSize: 0,
      maxDataSize: 2097152,
      pauseStreams: true,
      _released: true,
      _streams: [],
      _currentStream: null,
      _insideLoop: false,
      _pendingNext: false,
      _boundary: '--------------------------110961263845962053662763',
      _events: [Object: null prototype],
      _eventsCount: 1
    },
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'multipart/form-data; boundary=--------------------------110961263845962053662763',
      'User-Agent': 'axios/0.19.2'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function (anonymous)],
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      error: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 6,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: true,
    shouldKeepAlive: false,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'siasky.net',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'siasky.net',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 54,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'POST /skynet/skyfile?filename=%2FUsers%2Fls%2Fcode%2Fsrc%2Fltfschoen%2Fethquad%2Fclient%2Fbuild HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: multipart/form-data; boundary=--------------------------110961263845962053662763\r\n' +
      'User-Agent: axios/0.19.2\r\n' +
      'Host: siasky.net\r\n' +
      'Connection: close\r\n' +
      'Transfer-Encoding: chunked\r\n' +
      '\r\n',
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/skynet/skyfile?filename=%2FUsers%2Fls%2Fcode%2Fsrc%2Fltfschoen%2Fethquad%2Fclient%2Fbuild',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 400,
      statusMessage: 'Bad Request',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://siasky.net/skynet/skyfile?filename=%2FUsers%2Fls%2Fcode%2Fsrc%2Fltfschoen%2Fethquad%2Fclient%2Fbuild',
      redirects: [],
      [Symbol(kCapture)]: false
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'siasky.net',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 4140895,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://siasky.net/skynet/skyfile?filename=%2FUsers%2Fls%2Fcode%2Fsrc%2Fltfschoen%2Fethquad%2Fclient%2Fbuild',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: true,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 400,
    statusText: 'Bad Request',
    headers: {
      'access-control-allow-headers': 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range',
      'access-control-allow-methods': 'GET, POST, OPTIONS, PUT, DELETE',
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'Content-Length,Content-Range',
      'content-length': '89',
      'content-type': 'application/json; charset=utf-8',
      date: 'Sun, 09 Aug 2020 04:03:58 GMT',
      server: 'Caddy',
      connection: 'close'
    },
    config: {
      url: 'https://siasky.net/skynet/skyfile',
      method: 'post',
      params: [Object],
      data: [FormData],
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      validateStatus: [Function: validateStatus]
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: true,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'POST /skynet/skyfile?filename=%2FUsers%2Fls%2Fcode%2Fsrc%2Fltfschoen%2Fethquad%2Fclient%2Fbuild HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: multipart/form-data; boundary=--------------------------110961263845962053662763\r\n' +
        'User-Agent: axios/0.19.2\r\n' +
        'Host: siasky.net\r\n' +
        'Connection: close\r\n' +
        'Transfer-Encoding: chunked\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/skynet/skyfile?filename=%2FUsers%2Fls%2Fcode%2Fsrc%2Fltfschoen%2Fethquad%2Fclient%2Fbuild',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'siasky.net',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: true,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: {
      message: 'invalid filename provided: [invalid path string; path cannot begin with /]'
    }
  },
  isAxiosError: true,
  toJSON: [Function (anonymous)]
}
```

**Comment by ltfschoen** [comment]
I just got it to work, it was breaking because if you don't pass the a property `customFilename` with a valid string value, then it uses the folder's path as the as the value (see this line of the source code https://github.com/NebulousLabs/nodejs-skynet/blob/master/src/upload.js#L69) (e.g. `params { filename: '/Users/ls/code/src/ltfschoen/ethquad/client/build' }`, but this breaks, and in the 404 error message it returns `'invalid filename provided: [invalid path string; path cannot begin with /]'`.

So it was necessary to pass the `customFilename` property with a simple string value as shown below to get it to work:

```
const uploadDirectoryToSkynet = async (directory) => {
  console.log('Uploading directory to Skynet: ', directory);
  const skylinkUrl = await skynet.uploadDirectory(
    directory,
    {
      APIKey: process.env.SKYNET_API_KEY,
      customFilename: "EthQuad-Website",
      customUserAgent: "Sia-Agent"
    }
  );
```

I'd recommend changing the source code here https://github.com/NebulousLabs/nodejs-skynet/blob/master/src/upload.js#L69 from `const params = { filename: opts.customFilename || path };` to `const params = { filename: opts.customFilename || 'filename' };` so just a simple string like `'filename'` is used as the fallback or similar.

**Comment by m-cat** [comment]
Thanks @ltfschoen. Are you passing an absolute or relative path to `uploadDirectory`? Relative paths should work for now.

> I'd recommend changing the source code here https://github.com/NebulousLabs/nodejs-skynet/blob/master/src/upload.js#L69 from const params = { filename: opts.customFilename || path }; to const params = { filename: opts.customFilename || 'filename' }; so just a simple string like 'filename' is used as the fallback or similar.

I don't think we should hardcode a default directory name here, we should be using the name of the directory. In the case of absolute directory paths we should probably just be removing the leading slash.
